#-------------------------------------------------
#
# Project created by QtCreator 2014-07-01T10:27:04
#
#-------------------------------------------------

QT += core widgets gui xml printsupport

TARGET = eNetEditor

TEMPLATE = app

RC_FILE = resources/icon.rc

SOURCES += \
    src/database/stops/busStopTable.cpp \
    src/database/stops/chargingStationTable.cpp \
    src/database/connectionTable.cpp \
    src/database/edges/edgeTable.cpp \
    src/database/vehicles/flowTable.cpp \
    src/database/nodeTable.cpp \
    src/database/prohibitionTable.cpp \
    src/database/routeTable.cpp \
    src/database/trafficLightTable.cpp \
    src/database/vehicles/vehicleTable.cpp \
    src/database/vehicleTypeTable.cpp \
    src/items/stops/busStopItem.cpp \
    src/items/stops/chargingStationItem.cpp \
    src/items/connectionItem.cpp \
    src/items/edges/edgeItem.cpp \
    src/items/edges/edgeTypeItem.cpp \
    src/items/laneItem.cpp \
    src/items/nodeItem.cpp \
    src/items/prohibitionItem.cpp \
    src/items/routeItem.cpp \
    src/items/trafficLightItem.cpp \
    src/items/vehicles/vehicleItem.cpp \
    src/items/vehicleTypeItem.cpp \
    src/items/vehicles/flowItem.cpp \
    src/tools/cadytsTool.cpp \
    src/tools/dfRouterTool.cpp \
    src/tools/duaRouterTool.cpp \
    src/tools/jtrRouterTool.cpp \
    src/tools/netConvertTool.cpp \
    src/parsing/trafficLightParsing.cpp \
    src/project/undoRedoProject.cpp \
    src/dialogs/project/scalaProjectDialog.cpp \
    src/dialogs/database/trafficLightTableDialog.cpp \
    src/extern/QCustomPlot.cpp \
    src/database/edges/edgeTypeTable.cpp \
    src/database/laneTable.cpp \
    src/project/itemManagerProject.cpp \
    src/main/eNetEditorMessages.cpp \
    src/dialogs/main/eNetEditorConfigurationDialog.cpp \
    src/dialogs/main/eNetEditorAboutDialog.cpp \
    src/dialogs/main/eNetEditorImportNetDialog.cpp \
    src/dialogs/main/eNetEditorNewFileDialog.cpp \
    src/dialogs/main/eNetEditorProcessingDialog.cpp \
    src/dialogs/main/eNetEditorStatisticsDialog.cpp \
    src/main/eNetEditorImportNet.cpp \
    src/database/eNetEditorDatabase.cpp \
    src/database/eNetEditorTable.cpp \
    src/items/eNetEditorItem.cpp \
    src/project/eNetEditorProject.cpp \
    src/tools/eNetEditorTool.cpp \
    src/tools/netGenerateTool.cpp \
    src/tools/sumoTool.cpp \
    src/dialogs/tools/eNetEditorToolDialog.cpp \
    src/dialogs/items/stops/busStopItemDialog.cpp \
    src/dialogs/items/stops/chargingStationItemDialog.cpp \
    src/dialogs/items/connectionItemDialog.cpp \
    src/dialogs/items/edges/edgeItemDialog.cpp \
    src/dialogs/items/vehicles/flowItemDialog.cpp \
    src/dialogs/items/laneItemDialog.cpp \
    src/dialogs/items/nodeItemDialog.cpp \
    src/dialogs/items/prohibitionItemDialog.cpp \
    src/dialogs/items/routeItemDialog.cpp \
    src/dialogs/items/trafficLightItemDialog.cpp \
    src/dialogs/items/vehicles/vehicleItemDialog.cpp \
    src/dialogs/items/vehicleTypeItemDialog.cpp \
    src/dialogs/tools/cadytsToolDialog.cpp \
    src/dialogs/tools/dfRouterToolDialog.cpp \
    src/dialogs/tools/duaRouterToolDialog.cpp \
    src/dialogs/tools/jtrRouterToolDialog.cpp \
    src/dialogs/tools/netConvertToolDialog.cpp \
    src/dialogs/tools/netGenerateToolDialog.cpp \
    src/dialogs/tools/sumoToolDialog.cpp \
    src/dialogs/items/eNetEditorItemDialog.cpp \
    src/dialogs/database/eNetEditorTableDialog.cpp \
    src/database/flowMeasureTable.cpp \
    src/items/flowMeasureItem.cpp \
    src/dialogs/items/flowMeasureItemDialog.cpp \
    src/items/distributionFunctionItem.cpp \
    src/dialogs/items/distributionFunctionItemDialog.cpp \
    src/project/eNetEditorScene.cpp \
    src/dialogs/database/nodeTableDialog.cpp \
    src/dialogs/database/laneTableDialog.cpp \
    src/dialogs/database/connectionTableDialog.cpp \
    src/dialogs/database/prohibitionTableDialog.cpp \
    src/dialogs/database/routeTableDialog.cpp \
    src/dialogs/database/stops/busStopTableDialog.cpp \
    src/dialogs/database/stops/chargingStationTableDialog.cpp \
    src/dialogs/database/edges/edgeTypeTableDialog.cpp \
    src/dialogs/database/flowMeasureTableDialog.cpp \
    src/configuration/tools/eNetEditorToolConfiguration.cpp \
    src/configuration/tools/cadytsToolConfiguration.cpp \
    src/configuration/tools/dfRouterToolConfiguration.cpp \
    src/configuration/tools/duaRouterToolConfiguration.cpp \
    src/configuration/tools/jtrRouterToolConfiguration.cpp \
    src/configuration/tools/netConvertToolConfiguration.cpp \
    src/configuration/tools/netGenerateToolConfiguration.cpp \
    src/configuration/tools/sumoToolConfiguration.cpp \
    src/configuration/items/nodeItemConfiguration.cpp \
    src/configuration/items/edges/edgeItemConfiguration.cpp \
    src/configuration/items/laneItemConfiguration.cpp \
    src/configuration/items/connectionItemConfiguration.cpp \
    src/configuration/items/prohibitionItemConfiguration.cpp \
    src/configuration/items/trafficLightItemConfiguration.cpp \
    src/configuration/items/routeItemConfiguration.cpp \
    src/configuration/items/stops/busStopItemConfiguration.cpp \
    src/configuration/items/stops/chargingStationItemConfiguration.cpp \
    src/configuration/items/vehicleTypeItemConfiguration.cpp \
    src/configuration/items/vehicles/vehicleItemConfiguration.cpp \
    src/configuration/items/vehicles/flowItemConfiguration.cpp \
    src/configuration/items/edges/edgeTypeItemConfiguration.cpp \
    src/configuration/items/flowMeasureItemConfiguration.cpp \
    src/configuration/items/distributionFunctionItemConfiguration.cpp \
    src/configuration/items/eNetEditorItemConfiguration.cpp \
    src/dialogs/database/edges/edgeTableDialog.cpp \
    src/dialogs/database/vehicleTypeTableDialog.cpp \
    src/dialogs/database/vehicles/vehicleTableDialog.cpp \
    src/dialogs/database/vehicles/flowTableDialog.cpp \
    src/dialogs/database/distributionFunctionTableDialog.cpp \
    src/dialogs/items/edges/edgeVehicleTypesAllowedDialog.cpp \
    src/dialogs/items/edges/edgeTypeItemDialog.cpp \
    src/dialogs/main/eNetEditorLoadingDialog.cpp \
    src/main/eNetEditorThread.cpp \
    src/database/distributionFunctionTable.cpp \
    src/configuration/items/detectors/inductionLoopsE1DetectorItemConfiguration.cpp \
    src/configuration/items/detectors/laneAreaE2DetectorItemConfiguration.cpp \
    src/configuration/items/detectors/multiEntryExitE3DetectorItemConfiguration.cpp \
    src/database/detectors/inductionLoopsE1DetectorTable.cpp \
    src/database/detectors/laneAreaE2DetectorTable.cpp \
    src/dialogs/database/detectors/inductionLoopsE1DetectorTableDialog.cpp \
    src/dialogs/database/detectors/laneAreaE2DetectorTableDialog.cpp \
    src/dialogs/database/detectors/multiEntryExitE3DetectorTableDialog.cpp \
    src/dialogs/items/detectors/inductionLoopsE1DetectorItemDialog.cpp \
    src/dialogs/items/detectors/laneAreaE2DetectorItemDialog.cpp \
    src/dialogs/items/detectors/multiEntryExitE3DetectorItemDialog.cpp \
    src/items/detectors/inductionLoopsE1DetectorItem.cpp \
    src/items/detectors/laneAreaE2DetectorItem.cpp \
    src/items/detectors/multiEntryExitE3DetectorItem.cpp \
    src/database/detectors/multiEntryExitE3DetectorTable.cpp \
    src/dialogs/main/eNetEditorMainWindow.cpp \
    src/dialogs/eNetEditorDialog.cpp \
    src/configuration/main/eNetEditorMainConfiguration.cpp \
    src/configuration/project/eNetEditorProjectConfiguration.cpp \
    src/configuration/eNetEditorConfiguration.cpp \
    src/dialogs/project/eNetEditorProjectDialog.cpp \
    src/configuration/items/turnRatios/turnRatioItemConfiguration.cpp \
    src/database/turnRatios/turnRatioTable.cpp \
    src/dialogs/database/turnRatios/turnRatioTableDialog.cpp \
    src/items/turnRatios/turnRatioItem.cpp \
    src/main/main.cpp \
    src/main/eNetEditor.cpp \
    src/items/turnRatios/turnRatioIntervalItem.cpp \
    src/database/turnRatios/turnRatioIntervalTable.cpp \
    src/dialogs/database/turnRatios/turnRatioIntervalTableDialog.cpp \
    src/configuration/items/turnRatios/turnRatioIntervalItemConfiguration.cpp \
    src/configuration/items/turnRatios/abstractTurnRatioItemConfiguration.cpp \
    src/database/turnRatios/abstractTurnRatioTable.cpp \
    src/dialogs/database/turnRatios/abstractTurnRatioTableDialog.cpp \
    src/dialogs/database/vehicles/abstractVehicleTableDialog.cpp \
    src/dialogs/items/turnRatios/abstractTurnRatioItemDialog.cpp \
    src/items/turnRatios/abstractTurnRatioItem.cpp \
    src/items/vehicles/abstractVehicleItem.cpp \
    src/configuration/items/detectors/abstractDetectorItemConfiguration.cpp \
    src/configuration/items/edges/abstractEdgeItemConfiguration.cpp \
    src/configuration/items/vehicles/abstractVehicleItemConfiguration.cpp \
    src/database/detectors/abstractDetectorTable.cpp \
    src/database/edges/abstractEdgeTable.cpp \
    src/database/vehicles/abstractVehicleTable.cpp \
    src/dialogs/database/detectors/abstractDetectorTableDialog.cpp \
    src/dialogs/database/edges/abstractEdgeTableDialog.cpp \
    src/dialogs/items/detectors/abstractDetectorItemDialog.cpp \
    src/dialogs/items/edges/abstractEdgeItemDialog.cpp \
    src/dialogs/items/vehicles/abstractVehicleItemDialog.cpp \
    src/items/detectors/abstractDetectorItem.cpp \
    src/items/edges/abstractEdgeItem.cpp \
    src/dialogs/items/turnRatios/turnRatioItemDialog.cpp \
    src/dialogs/items/turnRatios/turnRatioIntervalDialog.cpp \
    src/dialogs/project/abstractProjectDialog.cpp \

HEADERS  += \
    src/database/stops/busStopTable.h \
    src/database/stops/chargingStationTable.h \
    src/database/connectionTable.h \
    src/database/edges/edgeTable.h \
    src/database/vehicles/flowTable.h \
    src/database/nodeTable.h \
    src/database/prohibitionTable.h \
    src/database/routeTable.h \
    src/database/trafficLightTable.h \
    src/database/vehicles/vehicleTable.h \
    src/database/vehicleTypeTable.h \
    src/items/stops/busStopItem.h \
    src/items/stops/chargingStationItem.h \
    src/items/connectionItem.h \
    src/items/edges/edgeItem.h \
    src/items/edges/edgeTypeItem.h \
    src/items/vehicles/flowItem.h \
    src/items/laneItem.h \
    src/items/nodeItem.h \
    src/items/prohibitionItem.h \
    src/items/routeItem.h \
    src/items/trafficLightItem.h \
    src/items/vehicles/vehicleItem.h \
    src/items/vehicleTypeItem.h \
    src/database/edges/edgeTypeTable.h \
    src/tools/cadytsTool.h \
    src/tools/dfRouterTool.h \
    src/tools/duaRouterTool.h \
    src/tools/jtrRouterTool.h \
    src/tools/netConvertTool.h \
    src/parsing/trafficLightParsing.h \
    src/project/undoRedoProject.h \
    src/dialogs/project/scalaProjectDialog.h \
    src/dialogs/database/trafficLightTableDialog.h \
    src/extern/QCustomPlot.h \
    src/database/laneTable.h \
    src/project/itemManagerProject.h \
    src/main/eNetEditorImportNet.h \
    src/main/eNetEditorMessages.h \
    src/dialogs/main/eNetEditorAboutDialog.h \
    src/dialogs/main/eNetEditorConfigurationDialog.h \
    src/dialogs/main/eNetEditorImportNetDialog.h \
    src/dialogs/main/eNetEditorNewFileDialog.h \
    src/dialogs/main/eNetEditorProcessingDialog.h \
    src/dialogs/main/eNetEditorStatisticsDialog.h \
    src/database/eNetEditorDatabase.h \
    src/database/eNetEditorTable.h \
    src/items/eNetEditorItem.h \
    src/project/eNetEditorProject.h \
    src/tools/eNetEditorTool.h \
    src/tools/sumoTool.h \
    src/tools/netGenerateTool.h \
    src/dialogs/tools/eNetEditorToolDialog.h \
    src/dialogs/items/stops/busStopItemDialog.h \
    src/dialogs/items/stops/chargingStationItemDialog.h \
    src/dialogs/items/connectionItemDialog.h \
    src/dialogs/items/edges/edgeItemDialog.h \
    src/dialogs/items/vehicles/flowItemDialog.h \
    src/dialogs/items/laneItemDialog.h \
    src/dialogs/items/nodeItemDialog.h \
    src/dialogs/items/prohibitionItemDialog.h \
    src/dialogs/items/routeItemDialog.h \
    src/dialogs/items/trafficLightItemDialog.h \
    src/dialogs/items/vehicles/vehicleItemDialog.h \
    src/dialogs/items/vehicleTypeItemDialog.h \
    src/dialogs/tools/cadytsToolDialog.h \
    src/dialogs/tools/dfRouterToolDialog.h \
    src/dialogs/tools/duaRouterToolDialog.h \
    src/dialogs/tools/jtrRouterToolDialog.h \
    src/dialogs/tools/netConvertToolDialog.h \
    src/dialogs/tools/netGenerateToolDialog.h \
    src/dialogs/tools/sumoToolDialog.h \
    src/dialogs/items/eNetEditorItemDialog.h \
    src/dialogs/database/eNetEditorTableDialog.h \
    src/database/flowMeasureTable.h \
    src/items/flowMeasureItem.h \
    src/dialogs/items/flowMeasureItemDialog.h \
    src/items/distributionFunctionItem.h \
    src/dialogs/items/distributionFunctionItemDialog.h \
    src/project/eNetEditorScene.h \
    src/dialogs/database/nodeTableDialog.h \
    src/dialogs/database/laneTableDialog.h \
    src/dialogs/database/connectionTableDialog.h \
    src/dialogs/database/prohibitionTableDialog.h \
    src/dialogs/database/routeTableDialog.h \
    src/dialogs/database/stops/busStopTableDialog.h \
    src/dialogs/database/stops/chargingStationTableDialog.h \
    src/dialogs/database/edges/edgeTypeTableDialog.h \
    src/dialogs/database/flowMeasureTableDialog.h \
    src/configuration/tools/eNetEditorToolConfiguration.h \
    src/configuration/tools/cadytsToolConfiguration.h \
    src/configuration/tools/dfRouterToolConfiguration.h \
    src/configuration/tools/duaRouterToolConfiguration.h \
    src/configuration/tools/jtrRouterToolConfiguration.h \
    src/configuration/tools/netConvertToolConfiguration.h \
    src/configuration/tools/netGenerateToolConfiguration.h \
    src/configuration/tools/sumoToolConfiguration.h \
    src/configuration/items/nodeItemConfiguration.h \
    src/configuration/items/edges/edgeItemConfiguration.h \
    src/configuration/items/laneItemConfiguration.h \
    src/configuration/items/connectionItemConfiguration.h \
    src/configuration/items/prohibitionItemConfiguration.h \
    src/configuration/items/trafficLightItemConfiguration.h \
    src/configuration/items/routeItemConfiguration.h \
    src/configuration/items/stops/busStopItemConfiguration.h \
    src/configuration/items/stops/chargingStationItemConfiguration.h \
    src/configuration/items/vehicleTypeItemConfiguration.h \
    src/configuration/items/vehicles/vehicleItemConfiguration.h \
    src/configuration/items/vehicles/flowItemConfiguration.h \
    src/configuration/items/edges/edgeTypeItemConfiguration.h \
    src/configuration/items/flowMeasureItemConfiguration.h \
    src/configuration/items/distributionFunctionItemConfiguration.h \
    src/configuration/items/eNetEditorItemConfiguration.h \
    src/dialogs/database/edges/edgeTableDialog.h \
    src/dialogs/database/vehicleTypeTableDialog.h \
    src/dialogs/database/vehicles/vehicleTableDialog.h \
    src/dialogs/database/vehicles/flowTableDialog.h \
    src/dialogs/database/distributionFunctionTableDialog.h \
    src/dialogs/items/edges/edgeVehicleTypesAllowedDialog.h \
    src/dialogs/items/edges/edgeTypeItemDialog.h \
    src/dialogs/main/eNetEditorLoadingDialog.h \
    src/main/eNetEditorThread.h \
    src/database/distributionFunctionTable.h \
    src/configuration/items/detectors/inductionLoopsE1DetectorItemConfiguration.h \
    src/configuration/items/detectors/laneAreaE2DetectorItemConfiguration.h \
    src/configuration/items/detectors/multiEntryExitE3DetectorItemConfiguration.h \
    src/database/detectors/inductionLoopsE1DetectorTable.h \
    src/database/detectors/laneAreaE2DetectorTable.h \
    src/database/detectors/multiEntryExitE3DetectorTable.h \
    src/dialogs/database/detectors/inductionLoopsE1DetectorTableDialog.h \
    src/dialogs/database/detectors/laneAreaE2DetectorTableDialog.h \
    src/dialogs/database/detectors/multiEntryExitE3DetectorTableDialog.h \
    src/dialogs/items/detectors/inductionLoopsE1DetectorItemDialog.h \
    src/dialogs/items/detectors/laneAreaE2DetectorItemDialog.h \
    src/dialogs/items/detectors/multiEntryExitE3DetectorItemDialog.h \
    src/items/detectors/inductionLoopsE1DetectorItem.h \
    src/items/detectors/laneAreaE2DetectorItem.h \
    src/items/detectors/multiEntryExitE3DetectorItem.h \
    src/dialogs/main/eNetEditorMainWindow.h \
    src/dialogs/eNetEditorDialog.h \
    src/configuration/main/eNetEditorMainConfiguration.h \
    src/configuration/project/eNetEditorProjectConfiguration.h \
    src/configuration/eNetEditorConfiguration.h \
    src/dialogs/project/eNetEditorProjectDialog.h \
    src/configuration/items/turnRatios/turnRatioItemConfiguration.h \
    src/database/turnRatios/turnRatioTable.h \
    src/dialogs/database/turnRatios/turnRatioTableDialog.h \
    src/items/turnRatios/turnRatioItem.h \
    src/main/eNetEditor.h \
    src/items/turnRatios/turnRatioIntervalItem.h \
    src/database/turnRatios/turnRatioIntervalTable.h \
    src/dialogs/database/turnRatios/turnRatioIntervalTableDialog.h \
    src/configuration/items/turnRatios/turnRatioIntervalItemConfiguration.h \
    src/configuration/items/turnRatios/abstractTurnRatioItemConfiguration.h \
    src/database/detectors/abstractDetectorTable.h \
    src/database/edges/abstractEdgeTable.h \
    src/database/turnRatios/abstractTurnRatioTable.h \
    src/database/vehicles/abstractVehicleTable.h \
    src/dialogs/database/detectors/abstractDetectorTableDialog.h \
    src/dialogs/database/edges/abstractEdgeTableDialog.h \
    src/dialogs/database/turnRatios/abstractTurnRatioTableDialog.h \
    src/dialogs/database/vehicles/abstractVehicleTableDialog.h \
    src/dialogs/items/edges/abstractEdgeItemDialog.h \
    src/dialogs/items/turnRatios/abstractTurnRatioItemDialog.h \
    src/dialogs/items/vehicles/abstractVehicleItemDialog.h \
    src/items/detectors/abstractDetectorItem.h \
    src/dialogs/items/detectors/abstractDetectorItemDialog.h \
    src/items/edges/abstractEdgeItem.h \
    src/items/turnRatios/abstractTurnRatioItem.h \
    src/items/vehicles/abstractVehicleItem.h \
    src/configuration/items/detectors/abstractDetectorItemConfiguration.h \
    src/configuration/items/edges/abstractEdgeItemConfiguration.h \
    src/configuration/items/vehicles/abstractVehicleItemConfiguration.h \
    src/dialogs/items/turnRatios/turnRatioItemDialog.h \
    src/dialogs/items/turnRatios/turnRatioIntervalDialog.h \
    src/dialogs/project/abstractProjectDialog.h \
    src/dialogs/project/scalaProjectDialog.h

FORMS    += \
    src/dialogs/database/trafficLightTableDialog.ui \
    src/dialogs/main/eNetEditorAboutDialog.ui \
    src/dialogs/main/eNetEditorConfigurationDialog.ui \
    src/dialogs/main/eNetEditorImportNetDialog.ui \
    src/dialogs/main/eNetEditorNewFileDialog.ui \
    src/dialogs/main/eNetEditorProcessingDialog.ui \
    src/dialogs/main/eNetEditorStatisticsDialog.ui \
    src/dialogs/items/stops/busStopItemDialog.ui \
    src/dialogs/items/stops/chargingStationItemDialog.ui \
    src/dialogs/items/connectionItemDialog.ui \
    src/dialogs/items/edges/edgeItemDialog.ui \
    src/dialogs/items/vehicles/flowItemDialog.ui \
    src/dialogs/items/laneItemDialog.ui \
    src/dialogs/items/nodeItemDialog.ui \
    src/dialogs/items/prohibitionItemDialog.ui \
    src/dialogs/items/routeItemDialog.ui \
    src/dialogs/items/trafficLightItemDialog.ui \
    src/dialogs/items/vehicles/vehicleItemDialog.ui \
    src/dialogs/items/vehicleTypeItemDialog.ui \
    src/dialogs/tools/cadytsToolDialog.ui \
    src/dialogs/tools/dfRouterToolDialog.ui \
    src/dialogs/tools/duaRouterToolDialog.ui \
    src/dialogs/tools/jtrRouterToolDialog.ui \
    src/dialogs/tools/netConvertToolDialog.ui \
    src/dialogs/tools/netGenerateToolDialog.ui \
    src/dialogs/tools/sumoToolDialog.ui \
    src/dialogs/items/flowMeasureItemDialog.ui \
    src/dialogs/items/distributionFunctionItemDialog.ui \
    src/dialogs/database/nodeTableDialogledialog.ui \
    src/dialogs/database/laneTableDialog.ui \
    src/dialogs/database/connectionTableDialog.ui \
    src/dialogs/database/prohibitionTableDialog.ui \
    src/dialogs/database/routeTableDialog.ui \
    src/dialogs/database/stops/busStopTableDialog.ui \
    src/dialogs/database/stops/chargingStationTableDialog.ui \
    src/dialogs/database/edges/edgeTypeTableDialog.ui \
    src/dialogs/database/flowMeasureTableDialog.ui \
    src/dialogs/database/edges/edgeTableDialog.ui \
    src/dialogs/database/vehicleTypeTableDialog.ui \
    src/dialogs/database/vehicles/vehicleTableDialog.ui \
    src/dialogs/database/vehicles/flowTableDialog.ui \
    src/dialogs/database/distributionFunctionTableDialog.ui \
    src/dialogs/items/edges/edgeVehicleTypesAllowedDialog.ui \
    src/dialogs/items/edges/edgeTypeItemDialog.ui \
    src/dialogs/main/eNetEditorLoadingDialog.ui \
    src/dialogs/database/detectors/inductionLoopsE1DetectorTableDialog.ui \
    src/dialogs/database/detectors/laneAreaE2DetectorTableDialog.ui \
    src/dialogs/database/detectors/multiEntryExitE3DetectorTableDialog.ui \
    src/dialogs/items/detectors/inductionLoopsE1DetectorItemDialog.ui \
    src/dialogs/items/detectors/laneAreaE2DetectorItemDialog.ui \
    src/dialogs/items/detectors/multiEntryExitE3DetectorItemDialog.ui \
    src/dialogs/main/eNetEditorMainWindow.ui \
    src/dialogs/project/eNetEditorProjectDialog.ui \
    src/dialogs/database/turnRatios/turnRatioTableDialog.ui \
    src/dialogs/database/turnRatios/turnRatioIntervalTableDialog.ui \
    src/dialogs/items/turnRatios/turnRatioItemDialog.ui \
    src/dialogs/items/turnRatios/turnRatioIntervalDialog.ui \
    src/dialogs/project/scalaProjectDialog.ui

OTHER_FILES +=

RESOURCES += \
    resources/eNetEditorResources.qrc

DISTFILES +=
